//
//  Fraises.swift
//  fraise
//
//  Created by Matt Wang on 2019-07-31.
//  Copyright © 2019 Matthew Wang. All rights reserved.
//

struct Fraises{
     static let general = [
        "salsa",
        "coffee mug",
        "hockey stick",
        "screw",
        "trampoline",
        "options",
        "airpods",
        "goggles",
        "pizza",
        "fried rice",
        "cutting board",
        "water bottles",
        "pineapple",
        "coffee bean",
        "dress shoe",
        "board game",
        "laser",
        "toilet bowl",
        "bluetooth speaker",
        "sugar cube",
        "phrase",
        "running shoes",
        "hawaiian shirt",
        "water filter",
        "pancake mix",
        "flip phone",
        "whole number",
        "rook",
        "melon",
        "outlet store",
        "microwave oven",
        "dog walker",
        "public speaking",
        "laptop charger",
        "variable",
        "sugar cube",
        "movie theater",
        "banana bread",
        "stir-fry",
        "recycling bin",
        "passenger door",
        "electric scooter",
        "blinds",
        "palm trees",
        "laundromat",
        "telephone pole",
        "spaghetti strainer",
        "bed frame",
        "chandelier",
        "tie clip",
        "fire extinguisher",
        "small intestine",
        "water fountain",
        "cheese block",
        "milk carton",
        "suede",
        "bean burrito",
        "hair tie",
        "knife sharpener",
        "basketball hoop",
        "swing dance",
        "kale",
        "stranger things",
        "canal",
        "panama",
        "suspension bridge",
        "mop",
        "cereal box",
        "disinfectant",
        "succulent",
        "thermostat",
        "standing desk",
        "cookie mix",
        "cookie cutter",
        "snare drum",
        "blog",
        "ampersand",
        "bounce house",
        "get out",
        "converses",
        "grandfather clock",
        "angry react",
        "direct message",
        "laser cutter",
        "acorn",
        "aloe vera",
        "dam",
        "granola bar",
        "trail mix",
        "oatmeal",
        "hot pot",
        "dumbbell",
        "roller blades",
        "ice skating",
        "ceiling fan",
        "orange county",
        "racks"
    ]
    static let songs = [
        "god's plan",
        "stayin' alive",
        "smooth criminal",
        "cocoa butter kisses",
        "sunday candy",
        "back in black",
        "get lucky",
        "mr. blue sky",
        "can't feel my face",
        "nine in the afternoon",
        "ultralight beam",
        "the chain",
        "a lot",
        "electric love",
        "count on me",
        "young dumb & broke",
        "the only exception",
        "stolen dance",
        "rocket man",
        "sweet caroline",
        "waterfalls",
        "take a chance on me",
        "marry you",
        "pumped up kicks",
        "lean on",
        "electric feel",
        "can't sleep love",
        "lost in japan",
        "feel it still",
        "take a walk",
        "royals",
        "thank u, next",
        "paper planes",
        "drops of jupiter",
        "cake by the ocean",
        "i will survive",
        "shooting stars"
    ]
    static let movies = [
        "the princess bride",
        "lion king",
        "death star",
        "good will hunting",
        "the hangover",
        "the notebook",
        "mulan",
        "kill bill",
        "forrest gump",
        "crazy rich asians",
        "black hawk down",
        "hurt locker",
        "the godfather",
        "spirited away",
        "the shawshank redemption",
        "the shining",
        "the dark knight",
        "inception",
        "terminator",
        "taxi driver",
        "moonlight",
        "la la land",
        "home alone",
        "pulp fiction",
        "back to the future",
        "mama mia",
        "rain man",
        "saving private ryan",
        "fight club",
        "black panther",
        "life of pi",
        "interstellar",
        "avatar",
        "jaws"
    ]
}
