//
//  Fraises.swift
//  fraise
//
//  Created by Matt Wang on 2019-07-31.
//  Copyright © 2019 Matthew Wang. All rights reserved.
//

struct Fraises{
     static let general = [
        "coffee mug",
        "hockey stick",
        "screw",
        "options",
        "cutting board",
        "airpods",
        "goggles",
        "water bottles",
        "coffee bean",
        "dress shoe",
        "board game",
        "laser",
        "toilet bowl",
        "bluetooth speaker",
        "phrase",
        "running shoes",
        "hawaiian shirt",
        "water filter",
        "flip phone",
        "whole number",
        "rook",
        "outlet store",
        "microwave oven",
        "dog walker",
        "public speaking",
        "laptop charger",
        "variable",
        "movie theater",
        "recycling bin",
        "passenger door",
        "electric scooter",
        "blinds",
        "palm trees",
        "laundromat",
        "telephone pole",
        "spaghetti strainer",
        "bed frame",
        "chandelier",
        "tie clip",
        "fire extinguisher",
        "small intestine",
        "water fountain",
        "suede",
        "hair tie",
        "knife sharpener",
        "basketball hoop",
        "swing dance",
        "stranger things",
        "canal",
        "panama",
        "suspension bridge",
        "mop",
        "disinfectant",
        "succulent",
        "thermostat",
        "standing desk",
        "cookie cutter",
        "snare drum",
        "blog",
        "ampersand",
        "bounce house",
        "converses",
        "grandfather clock",
        "angry react",
        "direct message",
        "laser cutter",
        "acorn",
        "aloe vera",
        "dam",
        "hot pot",
        "dumbbell",
        "roller blades",
        "ceiling fan",
        "orange county",
        "racks",
        "pull out couch",
        "television stand",
        "lock",
        "3d printer",
        "hand sanitizer",
        "duct",
        "stadium",
        "mitochondria",
        "download",
        "street art",
        "public transit",
        "late penalty",
        "doctor's note",
        "chute",
        "footstool",
        "saw",
        "wildfire",
        "power outlet",
        "fanny pack",
        "cash register"
    ]
    static let songs = [
        "god's plan",
        "stayin' alive",
        "smooth criminal",
        "cocoa butter kisses",
        "sunday candy",
        "back in black",
        "get lucky",
        "mr. blue sky",
        "can't feel my face",
        "nine in the afternoon",
        "ultralight beam",
        "the chain",
        "a lot",
        "electric love",
        "count on me",
        "young dumb & broke",
        "the only exception",
        "stolen dance",
        "rocket man",
        "sweet caroline",
        "waterfalls",
        "take a chance on me",
        "marry you",
        "pumped up kicks",
        "lean on",
        "electric feel",
        "can't sleep love",
        "lost in japan",
        "feel it still",
        "take a walk",
        "royals",
        "thank u, next",
        "paper planes",
        "drops of jupiter",
        "cake by the ocean",
        "i will survive",
        "shooting stars",
        "toxic",
        "sk8er boi",
        "mr. brightside",
        "i want you back",
        "straight outta compton",
        "take on me",
        "tainted love",
        "west end girls",
        "dancing queen",
        "yesterday",
        "imagine",
        "here comes the sun",
        "yellow submarine",
        "octopus's garden"
    ]
    static let movies = [
        "the princess bride",
        "lion king",
        "death star",
        "get out",
        "good will hunting",
        "the hangover",
        "the notebook",
        "mulan",
        "kill bill",
        "forrest gump",
        "crazy rich asians",
        "black hawk down",
        "hurt locker",
        "the godfather",
        "spirited away",
        "the shawshank redemption",
        "the shining",
        "the dark knight",
        "inception",
        "terminator",
        "taxi driver",
        "moonlight",
        "la la land",
        "home alone",
        "pulp fiction",
        "back to the future",
        "mama mia",
        "rain man",
        "saving private ryan",
        "fight club",
        "black panther",
        "life of pi",
        "interstellar",
        "avatar",
        "jaws",
        "blade runner",
        "moonrise kingodm",
        "shutter island",
        "casino royale",
        "wonder woman",
        "iron man",
        "the black pearl",
        "transformers",
        "apocalypse now",
        "the great escape",
        "memento",
        "finding nemo",
        "the incredibles",
        "toy story",
        "the pink panther",
        "space jam",
        "star trek"
    ]
    static let books = [
        "fifty shades of gray",
        "to kill a mockingbird",
        "pride and prejudice",
        "war and peace",
        "great expectations",
        "hunger games",
        "harry potter",
        "percy jackson",
        "moby dick",
        "oliver twist",
        "lord of the flies",
        "hamlet",
        "the lightning thief",
        "goblet of fire",
        "the scarlet letter",
        "lord of the rings",
        "the golden compass",
        "the twits",
        "holes",
        "heart of darkness",
        "dune",
        "the left hand of darkness",
        "the handmaid's tale",
        "fahrenheit 451",
        "1984",
        "animal farm",
        "brave new world",
        "war of the worlds",
        "the trial",
        "crime and punishment",
        "tinker tailor soldier spy",
        "the lorax",
        "green eggs and ham",
        "the cat in the hat",
        "the hungry caterpillar",
        "fantastic mr. fox",
        "anne of green gables",
        "treasure island",
        "2001: a space odyssey",
        "the secret agent",
        "inferno",
        "frankenstein",
        "dracula",
        "the count of monte cristo",
        "the three musketeers",
        "gone with the wind",
        "little women",
        "sherlock holmes",
        "a study in scarlet",
        "the odyssey",
        "order of the phoenix",
        "on the road",
        "of mice and men"
    ]
    static let sports = [
        "archery",
        "curling",
        "triatholon",
        "synchronised swimming",
        "water polo",
        "mountain biking",
        "trampoline",
        "boxing",
        "fencing",
        "golf",
        "field hockey",
        "sailing",
        "squash",
        "ice skating",
        "table tennis",
        "cricket",
        "figure skating",
        "polo",
        "volleyball",
        "gymnastics",
        "rowing",
        "ski jumping",
        "skeleton",
        "bowling",
        "cheerleading",
        "roller hockey",
        "ultimate frisbee",
        "softball"
    ]
    static let food = [
        "salsa",
        "pizza",
        "fried rice",
        "pineapple",
        "pancake mix",
        "sugar cube",
        "granola bar",
        "trail mix",
        "oatmeal",
        "cookie mix",
        "cereal box",
        "cheese block",
        "bean burrito",
        "kale",
        "milk carton",
        "banana bread",
        "stir-fry",
        "melon",
        "impossible meat",
        "tofu",
        "honeydew",
        "burrito bowl",
        "curry",
        "juice cleanse",
        "cream cheese",
        "almond milk",
        "protein powder",
        "rhubarb",
        "vinegar",
        "tiramisu",
        "black forest cake",
        "omlette",
        "philly cheesesteak",
        "deep dish pizza",
        "gelato",
        "french toast",
        "açai bowl",
        "muffin",
        "fruit salad",
        "deviled eggs",
        "croissant",
        "asparagus",
        "pumpkin",
        "starfruit",
        "breadcrumbs"
    ]
}
